var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function bee_button(){canvas=document.getElementById("canvas");anim_container=document.getElementById("animation_container");dom_overlay_container=document.getElementById("dom_overlay_container");var comp=AdobeAn.getComposition("6BC819C217A143BBB61478709A1E5974");var lib=comp.getLibrary();handleComplete({},comp);}
function handleComplete(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.Module14();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);};function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function bee_across_screen(){canvas=document.getElementById("canvas2");anim_container=document.getElementById("animation_container2");dom_overlay_container=document.getElementById("dom_overlay_container2");var comp=AdobeAn.getComposition("1A881492B82D44AAB25201EC3CDC5281");var lib=comp.getLibrary();handleComplete2({},comp);}
function handleComplete2(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.FlyingBeesBetween23Module_V2();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(false,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function big_bug(){canvas=document.getElementById("canvas3");anim_container=document.getElementById("animation_container3");dom_overlay_container=document.getElementById("dom_overlay_container3");var comp=AdobeAn.getComposition("6BD4C96C6968429FA508C93D21051EE4");var lib=comp.getLibrary();handleComplete3({},comp);}
function handleComplete3(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.BigBug1();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function protocol_beehive(){canvas=document.getElementById("canvas4");anim_container=document.getElementById("animation_container4");dom_overlay_container=document.getElementById("dom_overlay_container4");var comp=AdobeAn.getComposition("8989430135BB44BCB83AB24ED803414A");var lib=comp.getLibrary();handleComplete4({},comp);}
function handleComplete4(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.Protocol_Behive();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage)
stage.addEventListener("tick",handleTick)
function handleTick(event){var cameraInstance=exportRoot.___camera___instance;if(cameraInstance)
{var stageCenter={'x':lib.properties.width/2,'y':lib.properties.height/2};if(cameraInstance._off!=null&&cameraInstance._off==true)
exportRoot.transformMatrix=new createjs.Matrix2D();else
{if(cameraInstance.pinToObject!==undefined)
{cameraInstance.x=cameraInstance.pinToObject.x+cameraInstance.pinToObject.pinOffsetX;cameraInstance.y=cameraInstance.pinToObject.y+cameraInstance.pinToObject.pinOffsetY;}
var mat=cameraInstance.getMatrix();mat.tx-=stageCenter.x;mat.ty-=stageCenter.y;var inverseMat=mat.invert();inverseMat.prependTransform(stageCenter.x,stageCenter.y,1,1,0,0,0,0,0);inverseMat.appendTransform(-stageCenter.x,-stageCenter.y,1,1,0,0,0,0,0);exportRoot.transformMatrix=inverseMat;}}}}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function team_hive(){canvas=document.getElementById("canvas5");anim_container=document.getElementById("animation_container5");dom_overlay_container=document.getElementById("dom_overlay_container5");var comp=AdobeAn.getComposition("EF4623A166D447B1A778A8E7A9AC1FC6");var lib=comp.getLibrary();handleComplete5({},comp);}
function handleComplete5(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.Team_Beehive_3();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function team_fly(){canvas=document.getElementById("canvas6");anim_container=document.getElementById("animation_container6");dom_overlay_container=document.getElementById("dom_overlay_container6");var comp=AdobeAn.getComposition("7F429CD971DC405FB559DF2094C38E8A");var lib=comp.getLibrary();handleComplete6({},comp);}
function handleComplete6(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.Team_Bee_Fly_Annimation_2();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function partner_beehive(){canvas=document.getElementById("canvas7");anim_container=document.getElementById("animation_container7");dom_overlay_container=document.getElementById("dom_overlay_container7");var comp=AdobeAn.getComposition("211870B684DD4D2CA4285052639724AF");var lib=comp.getLibrary();handleComplete7({},comp);}
function handleComplete7(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.PartnerBeehiveAnimation_2();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function roadmap_animation(){canvas=document.getElementById("canvas8");anim_container=document.getElementById("animation_container8");dom_overlay_container=document.getElementById("dom_overlay_container8");var comp=AdobeAn.getComposition("2926F660274D47ECAFCA7CE54AF8F4C5");var lib=comp.getLibrary();handleComplete8({},comp);}
function handleComplete8(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.RECOVER_RoadmapAnimation_2();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function footer_bee(){canvas=document.getElementById("canvas9");anim_container=document.getElementById("animation_container9");dom_overlay_container=document.getElementById("dom_overlay_container9");var comp=AdobeAn.getComposition("FAB47CCEC37D40E8B8724F71AD485055");var lib=comp.getLibrary();handleComplete9({},comp);}
function handleComplete9(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.Footerbeeanimation();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function pre_loader(){canvas=document.getElementById("canvas10");anim_container=document.getElementById("animation_container10");dom_overlay_container=document.getElementById("dom_overlay_container10");var comp=AdobeAn.getComposition("A7EEE7FFEB6642FFA31690236E51879F");var lib=comp.getLibrary();handleComplete10({},comp);}
function handleComplete10(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.PreLoader();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);};function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function about_beehive(){canvas=document.getElementById("canvas11");anim_container=document.getElementById("animation_container11");dom_overlay_container=document.getElementById("dom_overlay_container11");var comp=AdobeAn.getComposition("264A9D7253E74CDBB3F1AD8E9B53443E");var lib=comp.getLibrary();handleComplete11({},comp);}
function handleComplete11(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.About_V2();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function token_beehive(){canvas=document.getElementById("canvas12");anim_container=document.getElementById("animation_container12");dom_overlay_container=document.getElementById("dom_overlay_container12");var comp=AdobeAn.getComposition("42F89C95A5CD46DBA73FA3033C7AC2DD");var lib=comp.getLibrary();handleComplete12({},comp);}
function handleComplete12(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib._8Token();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function big_bee_mobile(){canvas=document.getElementById("canvas13");anim_container=document.getElementById("animation_container13");dom_overlay_container=document.getElementById("dom_overlay_container13");var comp=AdobeAn.getComposition("14F03AADCB214955915D97C4975E4E58");var lib=comp.getLibrary();handleComplete13({},comp);}
function handleComplete13(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.BigBeeforMobile();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}
var canvas,stage,exportRoot,anim_container,dom_overlay_container,fnStartAnimation;function mobile_flower(){canvas=document.getElementById("canvas14");anim_container=document.getElementById("animation_container14");dom_overlay_container=document.getElementById("dom_overlay_container14");var comp=AdobeAn.getComposition("8D8C0CA61DE1435088BEBCF24F603C89");var lib=comp.getLibrary();handleComplete14({},comp);}
function handleComplete14(evt,comp){var lib=comp.getLibrary();var ss=comp.getSpriteSheet();exportRoot=new lib.MobileFlower_1();stage=new lib.Stage(canvas);fnStartAnimation=function(){stage.addChild(exportRoot);createjs.Ticker.setFPS(lib.properties.fps);createjs.Ticker.addEventListener("tick",stage);}
function makeResponsive(isResp,respDim,isScale,scaleType){var lastW,lastH,lastS=1;window.addEventListener('resize',resizeCanvas);resizeCanvas();function resizeCanvas(){var w=lib.properties.width,h=lib.properties.height;var iw=window.innerWidth,ih=window.innerHeight;var pRatio=window.devicePixelRatio||1,xRatio=iw/w,yRatio=ih/h,sRatio=1;if(isResp){if((respDim=='width'&&lastW==iw)||(respDim=='height'&&lastH==ih)){sRatio=lastS;}
else if(!isScale){if(iw<w||ih<h)
sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==1){sRatio=Math.min(xRatio,yRatio);}
else if(scaleType==2){sRatio=Math.max(xRatio,yRatio);}}
canvas.width=w*pRatio*sRatio;canvas.height=h*pRatio*sRatio;canvas.style.width=dom_overlay_container.style.width=anim_container.style.width=w*sRatio+'px';canvas.style.height=anim_container.style.height=dom_overlay_container.style.height=h*sRatio+'px';stage.scaleX=pRatio*sRatio;stage.scaleY=pRatio*sRatio;lastW=iw;lastH=ih;lastS=sRatio;stage.tickOnUpdate=false;stage.update();stage.tickOnUpdate=true;}}
makeResponsive(true,'both',false,1);AdobeAn.compositionLoaded(lib.properties.id);fnStartAnimation();}